### PR TITLE
Separated app and server & created a .env.example

### PR DESCRIPTION
**Pull request by ahmed-riad-1**

### CODE REVIEW

**Comment by wskinner74** [comment]
Linking the issue number so it shows up in the comment thread over there.

References issue #6

**Comment by ahmed-riad-1** [comment]
@wskinner74 I think you meant to reference #17 or #15.

**Comment by wskinner74** [comment]
Sorry, totally posted that comment in the wrong PR. Thanks for the heads up!

**Comment by ahmed-riad-1** [comment]
No problem 👍

**Comment by kg-kartik** [comment]
Sorry, but there is no need of this PR.

**Pull request closed without merging**
