### PR TITLE
Added All necessary topics for easy navigation of project

### PR DESCRIPTION
**Pull request by shriyaMadan**
Kindly review it and inform any changes that are needed.

### CODE REVIEW

**Comment by amanjagdev** [comment]
@shriyaMadan  The readme looks good enough but can you also add screenshots of the application, and the demo youtube video link
you can refer https://devfolio.co/submissions/stockify for the screenshots and youtube video link.

**Comment by shriyaMadan** [comment]
It's complete now.

**Comment by Krishna-Sivakumar** [comment]
I think the details provided in the readme are not enough to set up the development environment. 
To start the environment, a .env file needs to be created containing the URI of the database as mentioned [here](https://github.com/amanjagdev/stockify/issues/8#issuecomment-702063291). Or else, mongoose would throw an error.

**Comment by shriyaMadan** [comment]
okay my bad, am adding those steps now.

> I think the details provided in the readme are not enough to set up the development environment.
> To start the environment, a .env file needs to be created containing the URI of the database as mentioned [here](https://github.com/amanjagdev/stockify/issues/8#issuecomment-702063291).

**Comment by shriyaMadan** [comment]
Done!

> I think the details provided in the readme are not enough to set up the development environment.
> To start the environment, a .env file needs to be created containing the URI of the database as mentioned [here](https://github.com/amanjagdev/stockify/issues/8#issuecomment-702063291).

**Review by rajayush012 — CHANGES_REQUESTED** [review]
In line 136, you can add a guide for meaningful commit message. Refer this https://chris.beams.io/posts/git-commit/

**Comment by amanjagdev** [comment]
@shriyaMadan Great work...

PS: Star the project if you liked it.

**Pull request merged**
